version: '3.9'
services:
  postgres-local:
    image: postgres:16
    container_name: web_store_local_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: web_store_local_db
    volumes:
      - /c/Users/Vladimir/postgres-local:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: default@defaultmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8081:80"