spring:

  profiles:
    active: local

  flyway:
    enabled: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: AWqtLP+GFvnUBbpn1vbTpgmz8fwk6G14nQEVgJIBIVg=
  expiration: 86400000